"""
DarkTrust – Risk Context & Models

Defines the data structures used by the Adaptive Risk Engine.
"""

from enum import Enum
from pydantic import BaseModel, Field
from app.security.security_context import SecurityContext

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"

class RiskDecision(str, Enum):
    ALLOW = "ALLOW"
    CHALLENGE = "CHALLENGE"
    DENY = "DENY"

class RiskContext(BaseModel):
    """
    Extends the baseline SecurityContext with risk-specific metadata.
    """
    security_context: SecurityContext
    
    # Placeholder for future integration (e.g., from DB/AuditLogs)
    failed_login_attempts: int = Field(default=0, description="Recent failed logins")
    
    model_config = {
        "arbitrary_types_allowed": True
    }

class RiskResult(BaseModel):
    """
    The structured response generated by the Risk Engine.
    """
    score: int = Field(..., ge=0, le=100, description="Dynamic risk score (0-100)")
    level: RiskLevel
    decision: RiskDecision
    triggered_factors: list[str] = Field(default_factory=list, description="List of risk rules that added penalties")
